//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryHospitalizations
    {
        public int Id { get; set; }
        public int IdPatient { get; set; }
        public Nullable<System.DateTime> DateHospitalization { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string ReasonHospitalization { get; set; }
        public string DescriptionState { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
