//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.HistoryHospitalizations = new HashSet<HistoryHospitalizations>();
            this.MedicalDiagnosticProcedure = new HashSet<MedicalDiagnosticProcedure>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public double PassportNumber { get; set; }
        public int PassportSeries { get; set; }
        public string PlaceWorks { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int MedicalCardNumber { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public string InsurancePolicy { get; set; }
        public Nullable<System.DateTime> InsuranceExpirationDate { get; set; }
        public string Diagnosis { get; set; }
        public string HistoryDisease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryHospitalizations> HistoryHospitalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalDiagnosticProcedure> MedicalDiagnosticProcedure { get; set; }
    }
}
